services:

* type: web
  name: nexus-backend
  env: python
  branch: main
  instanceType: professional
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn main\:app --host 0.0.0.0 --port \$PORT
  envVars:

  * key: DB\_URL
    value: "\<POSTGRES\_URL>"
  * key: ML\_CLIENT\_ID
    value: "\<ML\_CLIENT\_ID>"
  * key: ML\_CLIENT\_SECRET
    value: "\<ML\_CLIENT\_SECRET>"
  * key: BACKEND\_URL
    value: "[https://nexus-backend.onrender.com](https://nexus-backend.onrender.com)"
  * key: FRONTEND\_URL
    value: "[https://nexus-dashboard.onrender.com](https://nexus-dashboard.onrender.com)"
  * key: WEB\_PASSWORD
    value: "\<WEB\_PASSWORD>"

* type: web
  name: nexus-dashboard
  env: python
  branch: main
  instanceType: professional
  buildCommand: pip install -r requirements.txt
  startCommand: streamlit run app.py --server.port \$PORT --server.enableCORS false
  envVars:

  * key: DB\_URL
    value: "\<POSTGRES\_URL>"
  * key: BACKEND\_URL
    value: "[https://nexus-backend.onrender.com](https://nexus-backend.onrender.com)"
  * key: FRONTEND\_URL
    value: "[https://nexus-dashboard.onrender.com](https://nexus-dashboard.onrender.com)"
  * key: WEB\_PASSWORD
    value: "\<WEB\_PASSWORD>"
